### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by BattleAxeVR** [nvpro-samples/vk_mini_samples#1]
Hi, I'm getting an error trying to build this sample:

1>perproject_globals.cpp
1>D:\1111\vk_samples\base_sample\src\vulkan_sample.hpp(40,27): error C2039: 'AppBaseVkCreateInfo': is not a member of 'nvvk' (compiling source file D:\1111\vk_samples\base_sample\src\main.cpp)
1>D:\1111\nvpro_core\nvvk/raypicker_vk.hpp(65): message : see declaration of 'nvvk' (compiling source file D:\1111\vk_samples\base_sample\src\main.cpp)
1>D:\1111\vk_samples\base_sample\src\vulkan_sample.hpp(40,46): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file D:\1111\vk_samples\base_sample\src\main.cpp)
1>D:\1111\vk_samples\base_sample\src\vulkan_sample.hpp(40,46): error C2143: syntax error: missing ',' before '&' (compiling source file D:\1111\vk_samples\base_sample\src\main.cpp)
1>D:\1111\vk_samples\base_sample\src\vulkan_sample.hpp(40,8): error C3668: 'VulkanSample::create': method with override specifier 'override' did not override any base class methods (compiling source file D:\1111\vk_samples\base_sample\src\main.cpp)

**Comment by mklefrancois** [comment]
Hi @BattleAxeVR , sorry for the errors. This comes from the repository nvpro_core which wasn't updated yet. Please pull the latest nvpro_core version and let me know if this fixes it.

**Comment by mklefrancois** [comment]
Closing, I don't think this exist anymore.
