### ISSUE TITLE
windows compilation failure

### ISSUE THREAD

**Issue by Masker0827** [nvpro-samples/vk_mini_samples#10]
I encountered an error when I used Clion to compile, how to solve it?
![EFQSAA6%1U2~3L`FUKY%%6C](https://github.com/nvpro-samples/vk_mini_samples/assets/121286985/41c4d2d5-1eac-41a8-8824-23fe164490ec)

**Comment by mklefrancois** [comment]
Quick question, do you have Vulkan SDK 1.3.275 installed?
