### ISSUE TITLE
Reimplement Optix Denoiser in Vulkan Compute 

### ISSUE THREAD

**Issue by ahcox** [nvpro-samples/vk_mini_samples#2]
Hi,

Great to have this repo out there. 

Is there any plan or chance of making a plan to get the denoiser from Optix ported over to Vulkan? It'd be a lot cleaner and more widely useful that way than accessed through CUDA interrop.

Thanks!

**Comment by mklefrancois** [comment]
Thanks @ahcox for the comments. The OptiX denoiser is based on [cuDNN ](https://developer.nvidia.com/cudnn) and I don't see a plan in short term to make a port to compute or a VulkanML version. I understand that the interop isn't great in a pure Vulkan environment, but it works pretty nicely.
